import type { Template, TinaField } from 'tinacms';
import { actionField, seoFields } from './shared-fields.template';

const cardsList = (name: string, label: string, fields: TinaField[], labelKey = 'title'): TinaField => ({
	type: 'object',
	name,
	label,
	list: true,
	ui: { itemProps: (item: Record<string, string>) => ({ label: item[labelKey] ?? '' }) },
	fields,
});

export const homeTemplate: Template = {
	name: 'home',
	label: 'Homepage',
	fields: [
		...seoFields(),
		{
			type: 'string',
			name: 'capsule',
			label: 'Quick-Answer Capsule',
			ui: { component: 'textarea' },
			description: 'Visually hidden summary for AI/answer engines. The phone number from Global Config is appended automatically.',
		},
		{
			type: 'object',
			name: 'hero',
			label: 'Hero',
			fields: [
				{ type: 'string', name: 'kicker', label: 'Kicker Badge' },
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				{ type: 'rich-text', name: 'body', label: 'Intro Paragraph' },
				{ type: 'string', name: 'video', label: 'Background Video', description: 'Path to the MP4, e.g. /uploads/…/hero.mp4' },
				{ type: 'image', name: 'poster', label: 'Video Poster Image', description: 'Also the page preload image (LCP).' },
				actionField('primary', 'Primary Button'),
				actionField('secondary', 'Secondary Link'),
			],
		},
		{
			type: 'object',
			name: 'trust',
			label: 'Trust Bar',
			fields: [
				{ type: 'string', name: 'lead', label: 'Lead Text' },
				cardsList('items', 'Rating Items', [
					{ type: 'string', name: 'name', label: 'Source Name' },
					{ type: 'string', name: 'sub', label: 'Sub-Line' },
				], 'name'),
			],
		},
		{
			type: 'object',
			name: 'why',
			label: 'Why Choose Us',
			fields: [
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				{ type: 'rich-text', name: 'lede', label: 'Intro Paragraph' },
				{ type: 'string', name: 'ledeTail', label: 'Bold Lead-In Line', ui: { component: 'textarea' } },
				cardsList('cards', 'Service Cards', [
					{ type: 'string', name: 'title', label: 'Title' },
					{ type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
					{ type: 'string', name: 'linkLabel', label: 'Link Label' },
					{ type: 'string', name: 'link', label: 'Link' },
				]),
				actionField('cta', 'Section Link'),
			],
		},
		{
			type: 'object',
			name: 'testimonial',
			label: 'Testimonials',
			fields: [
				{ type: 'string', name: 'video', label: 'Testimonial Video', description: 'Path to the MP4.' },
				{ type: 'image', name: 'videoPoster', label: 'Video Poster Image' },
				{ type: 'string', name: 'videoCaption', label: 'Video Caption' },
				{ type: 'string', name: 'statNumber', label: 'Stat Number', description: 'e.g. "750"' },
				{ type: 'string', name: 'statSuffix', label: 'Stat Suffix', description: 'e.g. "+"' },
				{ type: 'rich-text', name: 'statBody', label: 'Stat Text' },
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				cardsList('quotes', 'Quotes', [
					{ type: 'string', name: 'quote', label: 'Quote', ui: { component: 'textarea' } },
					{ type: 'string', name: 'src', label: 'Source Line' },
				], 'src'),
				actionField('moreLink', 'All Reviews Link'),
				actionField('cta', 'Section Link'),
			],
		},
		{
			type: 'object',
			name: 'seller',
			label: 'Seller Help',
			fields: [
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				{ type: 'string', name: 'lede', label: 'Intro Line' },
				{ type: 'string', name: 'quote', label: 'Quote', ui: { component: 'textarea' } },
				{ type: 'string', name: 'quoteSource', label: 'Quote Source' },
				cardsList('jobs', 'Jobs', [
					{ type: 'string', name: 'title', label: 'Title' },
					{ type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
				]),
				actionField('cta', 'Section Link'),
			],
		},
		{
			type: 'object',
			name: 'stats',
			label: 'Stats Band',
			fields: [
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				{ type: 'string', name: 'lede', label: 'Intro Paragraph', ui: { component: 'textarea' } },
				cardsList('items', 'Stats', [
					{ type: 'number', name: 'count', label: 'Count-Up To' },
					{ type: 'string', name: 'prefix', label: 'Count-Up Prefix', description: 'Prepended to the counted number, e.g. "$".' },
					{ type: 'string', name: 'suffix', label: 'Count-Up Suffix', description: 'Appended to the counted number, e.g. "M".' },
					{ type: 'string', name: 'tail', label: 'Static Suffix', description: 'Styled suffix shown after the number, e.g. "+".' },
					{ type: 'string', name: 'label', label: 'Label' },
				], 'label'),
				actionField('cta', 'Section Link'),
			],
		},
		{
			type: 'object',
			name: 'communities',
			label: 'Community Guides',
			fields: [
				{ type: 'string', name: 'eyebrow', label: 'Eyebrow' },
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				{ type: 'string', name: 'lede', label: 'Intro Paragraph', ui: { component: 'textarea' } },
				cardsList('cards', 'Community Cards', [
					{ type: 'image', name: 'image', label: 'Image' },
					{ type: 'string', name: 'alt', label: 'Image Alt Text' },
					{ type: 'number', name: 'width', label: 'Image Width (px)' },
					{ type: 'number', name: 'height', label: 'Image Height (px)' },
					{ type: 'string', name: 'title', label: 'City Name' },
					{ type: 'string', name: 'subtitle', label: 'Description' },
					{ type: 'string', name: 'link', label: 'Link' },
					{ type: 'string', name: 'linkLabel', label: 'Link Label', description: 'e.g. "Read the guide →"' },
				]),
				{ type: 'string', name: 'downloadsLabel', label: 'Downloads Label' },
				cardsList('downloads', 'Download Links', [
					{ type: 'string', name: 'label', label: 'Label' },
					{ type: 'string', name: 'link', label: 'File URL' },
				], 'label'),
				actionField('cta', 'Section Link'),
			],
		},
		{
			type: 'object',
			name: 'buyer',
			label: 'Buyer Help',
			fields: [
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				cardsList('steps', 'Steps', [
					{ type: 'string', name: 'title', label: 'Title' },
					{ type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
				]),
				{ type: 'string', name: 'quote', label: 'Quote', ui: { component: 'textarea' } },
				{ type: 'string', name: 'quoteSource', label: 'Quote Source' },
				actionField('cta', 'Section Link'),
			],
		},
		{
			type: 'object',
			name: 'team',
			label: 'Team Band',
			fields: [
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				{ type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
				actionField('primary', 'Primary Button'),
				actionField('secondary', 'Secondary Link'),
				{ type: 'string', name: 'video', label: 'Team Video', description: 'Path to the MP4.' },
				{ type: 'image', name: 'videoPoster', label: 'Video Poster Image' },
				{ type: 'string', name: 'videoCaption', label: 'Video Caption' },
			],
		},
		{
			type: 'object',
			name: 'market',
			label: 'Market Update',
			fields: [
				{ type: 'string', name: 'eyebrow', label: 'Eyebrow' },
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				{ type: 'rich-text', name: 'lede', label: 'Intro Paragraph' },
				{ type: 'string', name: 'source', label: 'Source Note' },
				cardsList('tiles', 'Market Tiles', [
					{ type: 'string', name: 'num', label: 'Number' },
					{ type: 'string', name: 'label', label: 'Label' },
					{ type: 'boolean', name: 'accent', label: 'Dark Tile' },
				], 'label'),
				{ type: 'string', name: 'takeaway', label: 'Takeaway', ui: { component: 'textarea' } },
				actionField('takeawayLink', 'Takeaway Link'),
			],
		},
		{
			type: 'object',
			name: 'fsbo',
			label: 'Agent vs FSBO',
			fields: [
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				{ type: 'string', name: 'lede', label: 'Intro Paragraph', ui: { component: 'textarea' } },
				{ type: 'string', name: 'agentPrice', label: 'Agent Price' },
				{ type: 'string', name: 'agentLabel', label: 'Agent Label' },
				{ type: 'string', name: 'soloPrice', label: 'FSBO Price' },
				{ type: 'string', name: 'soloLabel', label: 'FSBO Label' },
				{ type: 'string', name: 'caption', label: 'Caption', ui: { component: 'textarea' } },
				{ type: 'string', name: 'share', label: 'Share Paragraph', ui: { component: 'textarea' }, description: 'Wrap bold segments in **…**.' },
				cardsList('rows', 'Hardship Rows', [
					{ type: 'string', name: 'title', label: 'Title' },
					{ type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
				]),
				{ type: 'string', name: 'closeBody', label: 'Closing Line', ui: { component: 'textarea' } },
				actionField('closeCta', 'Closing Button'),
			],
		},
		{
			type: 'object',
			name: 'awards',
			label: 'Awards Wall',
			fields: [
				{ type: 'string', name: 'eyebrow', label: 'Eyebrow' },
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				{ type: 'string', name: 'lede', label: 'Intro Paragraph', ui: { component: 'textarea' } },
				{ type: 'number', name: 'monumentValue', label: 'Monument Number', description: 'The big counting numeral (e.g. 9).' },
				{ type: 'string', name: 'monumentSuffix', label: 'Monument Suffix', description: 'e.g. "times"' },
				{ type: 'string', name: 'monumentLabel', label: 'Monument Label' },
				{ type: 'string', name: 'monumentSub', label: 'Monument Sub-Label' },
				cardsList('trophies', 'Trophies', [
					{ type: 'string', name: 'org', label: 'Organization' },
					{ type: 'string', name: 'title', label: 'Title' },
					{ type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
					{ type: 'string', name: 'years', label: 'Year Chips', list: true, description: 'Optional year chips, e.g. 2017.' },
					{ type: 'boolean', name: 'featured', label: 'Featured Style' },
				]),
				{ type: 'string', name: 'footLine', label: 'Footer Line', description: 'Wrap the italic accent phrase in **…**.' },
				actionField('footLink', 'Footer Link'),
			],
		},
		{
			type: 'object',
			name: 'faq',
			label: 'FAQ Band',
			description: 'Also emitted as FAQPage structured data.',
			fields: [
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				cardsList('items', 'Questions', [
					{ type: 'string', name: 'question', label: 'Question' },
					{ type: 'rich-text', name: 'answer', label: 'Answer' },
				], 'question'),
				actionField('cta', 'Section Link'),
			],
		},
		{
			type: 'object',
			name: 'finalCta',
			label: 'Final CTA Band',
			fields: [
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				{ type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
				actionField('primary', 'Primary Button'),
				actionField('secondary', 'Secondary Link'),
				{ type: 'string', name: 'email', label: 'Contact Email', description: 'Shown under the button. Leave empty to fall back to Global Config.' },
			],
		},
		{
			type: 'object',
			name: 'next',
			label: 'Where To Go Next',
			fields: [
				{ type: 'string', name: 'heading', label: 'Heading', description: 'Wrap the italic accent phrase in **…**.' },
				cardsList('items', 'Rows', [
					{ type: 'string', name: 'title', label: 'Title' },
					{ type: 'string', name: 'body', label: 'Body', ui: { component: 'textarea' } },
					{ type: 'string', name: 'linkLabel', label: 'Link Label' },
					{ type: 'string', name: 'link', label: 'Link' },
				]),
			],
		},
		{
			type: 'object',
			name: 'agentSchema',
			label: 'Agent Structured Data',
			description: 'RealEstateAgent JSON-LD emitted on this page. Name, URL, phone and email come from Global Config.',
			fields: [
				{ type: 'string', name: 'description', label: 'Business Description', ui: { component: 'textarea' } },
				cardsList('areasServed', 'Areas Served', [
					{ type: 'string', name: 'name', label: 'Name', required: true },
					{ type: 'string', name: 'kind', label: 'Type', options: ['City', 'Place'], description: 'Schema.org place type.' },
				], 'name'),
				{ type: 'string', name: 'award', label: 'Awards Summary', ui: { component: 'textarea' } },
				{ type: 'string', name: 'rating', label: 'Aggregate Rating', description: 'e.g. "4.9"' },
				{ type: 'string', name: 'reviewCount', label: 'Review Count', description: 'e.g. "750"' },
			],
		},
	],
};
